 language: python
 python:
     - "2.7"
 os:
  - linux
 sudo: false
 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio
     - platformio update

 script:
     - platformio run clean
     - sed -i "s/\/\/#define AUTHENTICATION_FEATURE /#define AUTHENTICATION_FEATURE/g" $TRAVIS_BUILD_DIR/esp3d/config.h


notifications:
  email:
    on_success: change
    on_failure: change
